
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jun 29 23:42:58 CEST 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSPLUS = 34;
  public static final int LBRACKET = 41;
  public static final int CHAR = 50;
  public static final int CONST = 7;
  public static final int CASE = 19;
  public static final int LPAREN = 39;
  public static final int SEMI = 36;
  public static final int GREATER = 27;
  public static final int CONTINUE = 18;
  public static final int LESS = 29;
  public static final int MINUS = 21;
  public static final int RPAREN = 40;
  public static final int OROR = 32;
  public static final int BOOL = 49;
  public static final int COMMA = 37;
  public static final int CLASS = 4;
  public static final int DOTDOT = 46;
  public static final int DIV = 23;
  public static final int ANDAND = 31;
  public static final int NUM = 47;
  public static final int PLUS = 20;
  public static final int LESSEQ = 30;
  public static final int IF = 8;
  public static final int DOT = 38;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 35;
  public static final int RETURN = 15;
  public static final int RBRACKET = 42;
  public static final int NEW = 12;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 22;
  public static final int EQEQ = 25;
  public static final int MOD = 24;
  public static final int IDENT = 48;
  public static final int BREAK = 3;
  public static final int VOID = 16;
  public static final int EQ = 33;
  public static final int SWITCH = 9;
  public static final int LBRACE = 43;
  public static final int ELSE = 6;
  public static final int ENUM = 5;
  public static final int READ = 14;
  public static final int WHILE = 11;
  public static final int RBRACE = 44;
  public static final int EXTENDS = 17;
  public static final int QUESTION = 45;
  public static final int GREATEREQ = 28;
  public static final int PRINT = 13;
  public static final int DO = 10;
  public static final int NOTEQ = 26;
}

