
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Dec 17 14:22:56 CET 2017
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym_old {
  /* terminals */
  //kljucne reci 
  public static final int PROGRAM = 1;
  public static final int BREAK = 2;
  public static final int CLASS = 3;
  public static final int ENUM = 4;
  public static final int ELSE = 5;
  public static final int CONST = 6;
  public static final int IF = 7;
  public static final int SWITCH = 8;
  public static final int DO = 9;
  public static final int WHILE = 10;
  public static final int NEW = 11;
  public static final int PRINT = 12;
  public static final int READ = 13;
  public static final int RETURN = 14;
  public static final int VOID = 15;
  public static final int EXTENDS = 16;
  public static final int CONTINUE = 17;
  public static final int CASE = 18;
  //vrste tokena
  public static final int IDENT = 19;
  public static final int NUM = 20;
  public static final int CHAR = 21;
  public static final int BOOL = 22;
  //operatori
  public static final int PLUS = 23;
  public static final int MINUS = 24;
  public static final int MUL = 25;
  public static final int DIV = 26;
  public static final int MOD = 27;
  public static final int EQEQ = 28;
  public static final int NOTEQ = 29;
  public static final int GREATER = 30;
  public static final int GREATEREQ = 31;
  public static final int LESS = 32;
  public static final int LESSEQ = 33;
  public static final int ANDAND = 34;
  public static final int OROR = 35;
  public static final int EQ = 36;
  public static final int PLUSPLUS = 37;
  public static final int MINUSMINUS = 38;
  public static final int SEMI = 39;
  public static final int COMMA = 40;
  public static final int DOT = 41;
  public static final int LPAREN = 42;
  public static final int RPAREN = 43;
  public static final int LBRACKET = 44;
  public static final int RBRACKET = 45;
  public static final int LBRACE = 46;
  public static final int RBRACE = 47;
  public static final int QUESTION = 48;
  public static final int DOTDOT = 49;
  
  public static final int EOF = 50;
  
}

